//
//  ChipmunkViewModel.swift
//  Alvin
//
//  Created by Nareh Agazaryan on 1/30/22.
//

var chipmunkList: [Chipmunk] = [
    Chipmunk(name: "Alvin", description: "Alvin Seville is one of The Chipmunks and the overall main protagonist of the series and movies. He is the ringleader of the iconic trio. Alvin greatly relishes his role as band front man, and his impulsive behavior regularly gets him and his brothers (sometimes Dave) into trouble.\n\nAlvin retains some of the traits he possessed from the 80s, such as his desire for fun, and charm as seen in Alvin and the Chipmunks: The Squeakquel where he manages to capture the attention of a group of girls using his cute looks and as well as the French language (e.g. he called Becca Mademoiselle after kissing her finger). Nevertheless, he has difficulty at showing affection toward Dave such as in the first film, Alvin and the Chipmunks, where he struggles at telling Dave that he loves him as a father, but less so with his brothers such as the time Alvin tried to kiss Simon to cheer him up in the second film. In the third film, when all of the Chipmunks are stranded on the island, Alvin slowly becomes the mature one, as seen when he yells at Simon (who had a change in personality due to getting bitten by a spider), only for Brittany to tell him he's starting to sound like Dave - much to his horror (\"Nooooooooo!\") and builds the boys' treehouse by himself."),
    Chipmunk(name: "Simon", description: "Simon Seville is one of The Chipmunks and the overall deuteragonist of the series and films. He is the smartest of The Chipmunks, possessing an I.Q. just north of Einstein's. Simon possesses a very dry sense of humor, as well as a keen wit.\n\nSimon gets along great with Jeanette, who is smart, just like him. They are shy about their relationship, however it is obvious that he cares for her. Alvin exploits Simon's mastermind (less so than either series), though Simon secretly worries that they share the same gene pool. In Alvin and the Chipmunks, Simon is shown as a little less reserved and with a reduced higher intelligence at times (such as giving Dave a paperclip compass). Despite this, he still corrects people every now and again. His eyesight is so extremely poor as he's unable to see a toaster waffle fall directly in front of him without his glasses, which means that he's hyperopic or far-sighted. Simon's rivalry with Alvin isn't as bad as the 1980's and ALVINNN!!! and the Chipmunks series, but they butt heads at times. In Alvin and the Chipmunks: Chipwrecked, Simon has an alternate personality caused by a spider bite. His alternate identity goes by the name Simone, who speaks with a French accent and frequently flirts with Jeanette. Simone is depicted to be braver and less uptight than Simon. Near the end of the movie, Simon recovers from the bite and reverts back to his usual personality."),
    Chipmunk(name: "Theodore", description: "Theodore Seville is one of The Chipmunks and the overall tritagonist of the series and films. He is the youngest of the The Chipmunks and is best described as shy, sweet, kind, caring, loving, sensitive, gullible, trusting, naïve and innocent.\n\nTheodore is a chipmunk who helps out his brothers in their time of need. His primary instrument is the drum. His signature color is green. He is very gullible and innocent, always letting Alvin get to him with his schemes. He is shown to have nightmares (as well as frequent fears such as eagles and jungle monsters) and often sleeps with Dave in the first movie.He is shown in Alvin and the Chipmunks: The Squeakquel to be somewhat sensitive about his weight when the bullies poke his belly and butt and call him fat, even going as far as saying that he has \"serious junk in the trunk.\" Alvin and Simon get furious upon seeing their little brother get picked on because of his weight and claw them up as a result, taking care and watching after their little brother. He has a crush on Eleanor Miller, one of The Chipettes who has similar traits of Theodore, who shares his same interest, but not as gullible and she returns his feelings, but feels that he should stand up for himself more.")
]
